In [1]:
import pandas as pd

import os

import numpy as np

import networkx as nx

import matplotlib.pyplot as plt

from IPython.display import clear_output

In [4]:
file_index = 0

In [5]:
df_comments = pd.read_csv('data/get_comment_threads_output/comments_thread_sentiment_reduced_{}.csv'.format(file_index))

In [23]:
df_comments

,video_id,top_level_comment_id,author_display_name,sentiment
0,WyUyJKm-MiY,UgxmeuEGKaTnjr18AVZ4AaABAg,Imaan Jaffri,0
1,WyUyJKm-MiY,UgzlwPwyC3XlmzgzBr54AaABAg,Karlee Nash,0
2,WyUyJKm-MiY,UgynycPfXmKJePLzAEp4AaABAg,Bernice Ayer,1
3,WyUyJKm-MiY,UgwamwomyWMY8bpiPjp4AaABAg,Molly Seymour,1
4,WyUyJKm-MiY,Ugx7NWDtnzTkeACe5yJ4AaABAg,Charbonelle Weese,0
...,...,...,...,...
2056377,lOIFYf3sSnw,Ugw50lN281elkmpu2014AaABAg,Lovely .A,1
2056378,lOIFYf3sSnw,Ugx0MzMiJfba86UFRBp4AaABAg,Diana Thompson,1
2056379,lOIFYf3sSnw,UgzRG-y0DoBkLtpLl1J4AaABAg,AA W,0
2056380,lOIFYf3sSnw,UgwgoR1qaPAv3NPtEih4AaABAg,Brianna Taylor,0
2056381,lOIFYf3sSnw,UgyISvh5VI0F6SYtawl4AaABAg,SimplyRach,0

In [6]:
df_videos = pd.read_csv('data/get_videos_details/videos_details_computed.csv')

In [7]:
df_youtuber_videos = pd.read_csv('data/get_youtuber_videos_output/youtuber_videos.csv')

In [8]:
df_youtubers = pd.read_csv('data/get_youtubers_output/youtubers.csv')

In [10]:
first_graph = nx.DiGraph()

In [11]:
youtubers_name_set=set()
for youtuber in df_youtubers.values:
    youtubers_name_set.add(youtuber[0])

In [12]:
user_name_set= set()
nan_number=0
for comment in df_comments.values:
    if comment[2]!= None:
        user_name_set.add(comment[2])
    else:
        nan_number+=1

In [13]:
df_comments[df_comments.columns[2]].isnull().sum(axis = 0)#buono!

42

In [14]:
tot_nodes= list(youtubers_name_set.union(user_name_set))

In [15]:
#tolgo il nan
tot_nodes = tot_nodes[1:]

In [16]:
first_graph.add_nodes_from(tot_nodes)

In [17]:
youtuber_video_join=df_youtubers.set_index('channel_id').join(df_youtuber_videos.set_index('channel_id'), on='channel_id',lsuffix='_yt', rsuffix='_ytvd')

In [18]:
youtuber_video_join = youtuber_video_join[youtuber_video_join.columns[[0,2]]]

In [19]:
youtuber_video_join = youtuber_video_join.set_index('video_id').join(df_videos.set_index('video_id'),on='video_id',lsuffix='_yt', rsuffix='_ytvd')

In [20]:
youtuber_video_join

,display_name,category_id,topics,brands,youtubers
video_id,,,,,
WyUyJKm-MiY,jeffreestar,Entertainment,"['social media', 'music', 'review']",['jeffree star cosmetics'],[]
5mUQo6lQG-U,jeffreestar,Howto & Style,"['new product launch', 'lifestyle', 'review']",['jeffree star cosmetics'],[]
QhbR5TEAMco,jeffreestar,Howto & Style,"['pet', 'lifestyle']",[],[]
3qYykmHx5gc,jeffreestar,Entertainment,"['social media', 'lifestyle', 'review']",[],[]
SxixuClI2vA,jeffreestar,Howto & Style,"['lifestyle', 'review']","['colourpop cosmetics', 'jeffree star cosmetics']",[]
...,...,...,...,...,...
bm-3Qrr7EUA,maybellinenewyork,Howto & Style,['lifestyle'],[],[]
hkxRjDS_Cjw,maybellinenewyork,Howto & Style,['lifestyle'],[],[]
8kElrRAa1ws,maybellinenewyork,Howto & Style,[],[],[]
7x6tX5T7LOs,maybellinenewyork,Howto & Style,['lifestyle'],['maybelline'],[]
NSdUFKOkKnc,maybellinenewyork,Howto & Style,['lifestyle'],[],[]

In [39]:
youtuber_comments = youtuber_video_join.join(df_comments.set_index('video_id'),on='video_id',lsuffix='_ytvd', rsuffix='_comm')

In [40]:
youtuber_comments  = (youtuber_comments[youtuber_comments.columns[[0,2,3,4,6,7]]]).dropna()
youtuber_comments

,display_name,topics,brands,youtubers,author_display_name,sentiment
video_id,,,,,,
WyUyJKm-MiY,jeffreestar,"['social media', 'music', 'review']",['jeffree star cosmetics'],[],Imaan Jaffri,0.0
WyUyJKm-MiY,jeffreestar,"['social media', 'music', 'review']",['jeffree star cosmetics'],[],Karlee Nash,0.0
WyUyJKm-MiY,jeffreestar,"['social media', 'music', 'review']",['jeffree star cosmetics'],[],Bernice Ayer,1.0
WyUyJKm-MiY,jeffreestar,"['social media', 'music', 'review']",['jeffree star cosmetics'],[],Molly Seymour,1.0
WyUyJKm-MiY,jeffreestar,"['social media', 'music', 'review']",['jeffree star cosmetics'],[],Charbonelle Weese,0.0
...,...,...,...,...,...,...
lOIFYf3sSnw,Jackie Aina,"['lifestyle', 'review']",['fenty beauty'],[],Lovely .A,1.0
lOIFYf3sSnw,Jackie Aina,"['lifestyle', 'review']",['fenty beauty'],[],Diana Thompson,1.0
lOIFYf3sSnw,Jackie Aina,"['lifestyle', 'review']",['fenty beauty'],[],AA W,0.0
lOIFYf3sSnw,Jackie Aina,"['lifestyle', 'review']",['fenty beauty'],[],Brianna Taylor,0.0
lOIFYf3sSnw,Jackie Aina,"['lifestyle', 'review']",['fenty beauty'],[],SimplyRach,0.0

In [37]:
edges = []

In [43]:
#{'video_category':[row[1]],'topics':[row[2]],'brands':[row[3]],'youtubers':row[4],'sentiments':[row[6]],'mean_sentiment':np.mean([row[6]])}
#i duplicati li guardo quando metto gli edge del grafo (se esiste giÃ  l'edge, aggiungo altri dettagli)
#il mean sentiment lo valuterÃ² dopo
i = 1
for idx_for,row_1 in enumerate(youtuber_comments.values):
    print('Comment: {}/{}'.format(idx_for,len(youtuber_comments.values)))
    clear_output(wait=True)
    matches_topics = row_1[1]
    matches_brands = row_1[2]
    matches_youtubers = row_1[3]
    for row_2 in youtuber_comments.values[i:]:
        link = False
        details = {'youtubers':[],'topics':[],'brands':[]}
        common_topics = []
        common_brands = []
        common_youtubers = []
        if any(x in row_2[1] for x in matches_topics):
            link = True
            details['topics'].append(row_2[1])
        if any(x in row_2[2] for x in matches_brands):
            link = True
            details['brands'].append(row_2[2])
        if any(x in row_2[3] for x in matches_youtubers):
            link = True
            details['youtubers'].append(row_2[3])
        if row_1[0] == row_2[0]:
            link = True
            details['youtubers'].append(row_2[0])
        if link:
            edges.append([(row_1[4],row_2[4]),details])
    i += 1

KeyboardInterrupt

In [ ]:
edges