In [9]:
import pandas as pd

import os

import numpy as np

import networkx as nx

import matplotlib.pyplot as plt

from IPython.display import clear_output

In [2]:
file_index = 0

In [3]:
df_comments = pd.read_csv('data/get_comment_threads_output/comments_thread_sentiment_reduced_{}.csv'.format(file_index))

In [6]:
df_videos = pd.read_csv('data/get_videos_details/videos_details_computed.csv')

In [66]:
df_youtuber_videos = pd.read_csv('data/get_youtuber_videos_output/youtuber_videos.csv')

In [8]:
df_youtubers = pd.read_csv('data/get_youtubers_output/youtubers.csv')

In [70]:
df_videos

,video_id,category_id,topics,brands
0,WyUyJKm-MiY,Entertainment,"['social media', 'review']",['jeffree star cosmetics']
1,5mUQo6lQG-U,Howto & Style,"['new product launch', 'lifestyle', 'review']",['jeffree star cosmetics']
2,QhbR5TEAMco,Howto & Style,"['lifestyle', 'pet']",[]
3,3qYykmHx5gc,Entertainment,"['lifestyle', 'social media', 'review']",[]
4,SxixuClI2vA,Howto & Style,"['lifestyle', 'review']","['colourpop cosmetics', 'jeffree star cosmetics']"
...,...,...,...,...
1595,A-ZXP9vN7hg,Howto & Style,"['lifestyle', 'private life/information']",['mac cosmetics']
1596,LYHs9j3-bG4,Howto & Style,['lifestyle'],['mac cosmetics']
1597,qrWkDwpqAEI,Howto & Style,"['tutorial', 'lifestyle', 'review']","['mac cosmetics', 'pat mcgrath']"
1598,6OUQi5ymq7o,Howto & Style,"['lifestyle', 'get ready with me']","['mac cosmetics', 'urban decay']"
1599,EuqQv-7AJ1o,Howto & Style,"['lifestyle', 'get ready with me']",['mac cosmetics']

In [10]:
first_graph = nx.DiGraph()

In [21]:
youtubers_name_set=set()
for youtuber in df_youtubers.values:
    youtubers_name_set.add(youtuber[0])

In [41]:
user_name_set= set()
nan_number=0
for comment in df_comments.values:
    if comment[2]!= None:
        user_name_set.add(comment[2])
    else:
        nan_number+=1

In [49]:
df_comments[df_comments.columns[2]].isnull().sum(axis = 0)#buono!

42

In [78]:
tot_nodes= list(youtubers_name_set.union(user_name_set))

In [79]:
#tolgo il nan
tot_nodes = tot_nodes[1:]

In [80]:
first_graph.add_nodes_from(tot_nodes)

In [54]:
youtuber_video_join=df_youtubers.set_index('channel_id').join(df_youtuber_videos.set_index('channel_id'), on='channel_id',lsuffix='_yt', rsuffix='_ytvd')

In [59]:
youtuber_video_join = youtuber_video_join[youtuber_video_join.columns[[0,2]]]

In [61]:
youtuber_video_join = youtuber_video_join.set_index('video_id').join(df_videos.set_index('video_id'),on='video_id',lsuffix='_yt', rsuffix='_ytvd')

In [62]:
youtuber_video_join

,display_name,category_id,topics,brands
video_id,,,,
WyUyJKm-MiY,jeffreestar,Entertainment,"['social media', 'review']",['jeffree star cosmetics']
5mUQo6lQG-U,jeffreestar,Howto & Style,"['new product launch', 'lifestyle', 'review']",['jeffree star cosmetics']
QhbR5TEAMco,jeffreestar,Howto & Style,"['lifestyle', 'pet']",[]
3qYykmHx5gc,jeffreestar,Entertainment,"['lifestyle', 'social media', 'review']",[]
SxixuClI2vA,jeffreestar,Howto & Style,"['lifestyle', 'review']","['colourpop cosmetics', 'jeffree star cosmetics']"
...,...,...,...,...
bm-3Qrr7EUA,maybellinenewyork,NaN,NaN,NaN
hkxRjDS_Cjw,maybellinenewyork,NaN,NaN,NaN
8kElrRAa1ws,maybellinenewyork,NaN,NaN,NaN
7x6tX5T7LOs,maybellinenewyork,NaN,NaN,NaN
NSdUFKOkKnc,maybellinenewyork,NaN,NaN,NaN

In [64]:
youtuber_comments = youtuber_video_join.join(df_comments.set_index('video_id'),on='video_id',lsuffix='_ytvd', rsuffix='_comm')

In [65]:
youtuber_comments

,display_name,category_id,topics,brands,top_level_comment_id,author_display_name,sentiment
video_id,,,,,,,
WyUyJKm-MiY,jeffreestar,Entertainment,"['social media', 'review']",['jeffree star cosmetics'],UgxmeuEGKaTnjr18AVZ4AaABAg,Imaan Jaffri,0.0
WyUyJKm-MiY,jeffreestar,Entertainment,"['social media', 'review']",['jeffree star cosmetics'],UgzlwPwyC3XlmzgzBr54AaABAg,Karlee Nash,0.0
WyUyJKm-MiY,jeffreestar,Entertainment,"['social media', 'review']",['jeffree star cosmetics'],UgynycPfXmKJePLzAEp4AaABAg,Bernice Ayer,1.0
WyUyJKm-MiY,jeffreestar,Entertainment,"['social media', 'review']",['jeffree star cosmetics'],UgwamwomyWMY8bpiPjp4AaABAg,Molly Seymour,1.0
WyUyJKm-MiY,jeffreestar,Entertainment,"['social media', 'review']",['jeffree star cosmetics'],Ugx7NWDtnzTkeACe5yJ4AaABAg,Charbonelle Weese,0.0
...,...,...,...,...,...,...,...
bm-3Qrr7EUA,maybellinenewyork,NaN,NaN,NaN,NaN,NaN,NaN
hkxRjDS_Cjw,maybellinenewyork,NaN,NaN,NaN,NaN,NaN,NaN
8kElrRAa1ws,maybellinenewyork,NaN,NaN,NaN,NaN,NaN,NaN
7x6tX5T7LOs,maybellinenewyork,NaN,NaN,NaN,NaN,NaN,NaN
NSdUFKOkKnc,maybellinenewyork,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#aggiungi counter
edges = []
for idx_for,row in enumerate(youtuber_comments.values):
    print('Comment: {}/{}'.format(idx_for,len(youtuber_comments.values)))
    clear_output(wait=True)
    try:
        youtuber = row[0]
        user = row[5]
        arr = [(item[0][0],item[0][1]) for item in edges]
        if (user,youtuber) not in arr:
            edges.append([(user,youtuber),{'video_category':set(row[1]),'topics':set(row[2]),'brands':set(row[3]),'sentiments':[row[6]],'mean_sentiment':np.mean([row[6]])}])
        else:
            idx = arr.index((user,youtuber))
            edges[idx][1]['video_category'].add(row[1])
            edges[idx][1]['topics'].add(row[2])
            edges[idx][1]['brands'].add(row[3])
            edges[idx][1]['sentiments'].append(row[6])
            edges[idx][1]['mean_sentiment'] = np.mean(edges[idx][1]['sentiments'])
    except:
        print('NaN values')

In [ ]:
edges